### ISSUE TITLE
Copy Projects

### ISSUE THREAD

**Issue by firepicaso** [firepicaso/Social-Interaction-Capstone-Module2#21]
link to the GitHub project
https://github.com/firepicaso/Social-Interaction-Capstone-Module2/projects/1

We have 2 students in this group.
Student A: Fatuma Hussein (fatmahussein)
Studeb B: Mustakim Masum (firepicaso)

**Comment by bobb-Rob** [comment]
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @firepicaso and @fatmahussein , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ Very descriptive Kanban task cards
✅ Your work is well documented.

## Optional suggestions

Cheers and Happy coding!👏👏👏
